#!/bin/bash
function File {
    # think you are inside the file
    # change here
    echo "$#"
}

# do not change anything
if [ ! $# -lt 1 ]; then
     File $*
     exit 0
fi

#change here 
# here you can pass the arguments
bash arguments.sh Shell is fun
